app <- ShinyDriver$new("../../")
app$snapshotInit("creativepracticeStest")

app$snapshot()
app$setInputs(radio = "creativepractice")
app$snapshot()
app$setInputs(sess = 14)
app$snapshot()
app$setInputs(sessprep = 1)
app$snapshot()
app$setInputs(sesshours = 3)
app$snapshot()
app$setInputs(postsess = 1)
app$snapshot()
app$setInputs(add = "click")
app$snapshot()
