app <- ShinyDriver$new("../../")
app$snapshotInit("discussionStest")

app$snapshot()
app$setInputs(radio = "discussion")
app$snapshot()
app$setInputs(postformat = "2")
app$snapshot()
app$setInputs(discName = "test ")
app$setInputs(discName = "test name")
app$snapshot()
app$setInputs(postspersem = 14)
app$snapshot()
app$setInputs(add = "click")
app$snapshot()
