app <- ShinyDriver$new("../../")
app$snapshotInit("examItest")

app$snapshot()
app$setInputs(radio = "exam")
app$snapshot()
app$setInputs(examformat = "1")
app$snapshot()
app$setInputs(examName = "Final")
app$snapshot()
app$setInputs(exams = 1)
app$snapshot()
app$setInputs(examhours = 1)
app$setInputs(examhours = 10)
app$snapshot()
app$setInputs(examlength = 3)
app$snapshot()
app$setInputs(add = "click")
app$snapshot()
