app <- ShinyDriver$new("../../")
app$snapshotInit("LabStest")

app$snapshot()
app$setInputs(radio = "lab")
app$snapshot()
app$setInputs(labs = 14)
app$snapshot()
app$setInputs(labprep = 1)
app$snapshot()
app$setInputs(labhours = 3)
app$snapshot()
app$setInputs(postlab = 1)
app$snapshot()
app$setInputs(add = "click")
app$snapshot()
