app <- ShinyDriver$new("../../")
app$snapshotInit("quizStest")

app$snapshot()
app$setInputs(radio = "quiz")
app$snapshot()
app$setInputs(quizformat = "2")
app$snapshot()
app$setInputs(quizzes = 14)
app$snapshot()
app$setInputs(studyhours = 0.5)
app$snapshot()
app$setInputs(add = "click")
app$snapshot()
