app <- ShinyDriver$new("../../")
app$snapshotInit("readingtest_manuallyadjust")

app$snapshot()
app$setInputs(radio = "reading")
app$snapshot()
app$setInputs(readingName = "readings")
app$snapshot()
app$setInputs(weeklypages = 10)
app$snapshot()
app$setInputs(setreadingrate = TRUE)
app$snapshot()
app$setInputs(overridepagesperhour = 5)
app$snapshot()
app$setInputs(add = "click")
app$snapshot()
