app <- ShinyDriver$new("../../")
app$snapshotInit("readingtest_600wSomeUnder")

app$snapshot()
app$setInputs(radio = "reading")
app$snapshot()
app$setInputs(readingName = "readings")
app$snapshot()
app$setInputs(weeklypages = 10)
app$snapshot()
app$setInputs(readingdensity = "2")
app$snapshot()
app$setInputs(difficulty = "2")
app$snapshot()
app$setInputs(readingpurpose = "2")
app$snapshot()
app$setInputs(add = "click")
app$snapshot()
