app <- ShinyDriver$new("../../")
app$snapshotInit("readingtest_750wManyEngag")

app$snapshot()
app$setInputs(radio = "reading")
app$snapshot()
app$setInputs(readingName = "readings")
app$snapshot()
app$setInputs(weeklypages = 10)
app$snapshot()
app$setInputs(readingdensity = "3")
app$snapshot()
app$setInputs(difficulty = "3")
app$snapshot()
app$setInputs(readingpurpose = "3")
app$snapshot()
app$setInputs(add = "click")
app$snapshot()
