app <- ShinyDriver$new("../../")
app$snapshotInit("tutorialItest")

app$snapshot()
app$setInputs(radio = "tutorial")
app$snapshot()
app$setInputs(tutorials = 14)
app$snapshot()
app$setInputs(tutprep = 1)
app$snapshot()
app$setInputs(tuthours = 2)
app$snapshot()
app$setInputs(tutsynch = FALSE)
app$snapshot()
app$setInputs(add = "click")
app$snapshot()
