app <- ShinyDriver$new("../../")
app$snapshotInit("writingStest")

app$snapshot()
app$setInputs(radio = "writing")
app$snapshot()
app$setInputs(writingformat = "2")
app$snapshot()
app$setInputs(writingName = "writing")
app$snapshot()
app$setInputs(numassign = 5)
app$snapshot()
app$setInputs(preptime = 60)
app$snapshot()
app$setInputs(add = "click")
app$snapshot()
