app <- ShinyDriver$new("../../")
app$snapshotInit("writingItest_250wResExtD")

app$snapshot()
app$setInputs(radio = "writing")
app$snapshot()
app$setInputs(writingName = "writing")
app$snapshot()
app$setInputs(numassign = 5)
app$snapshot()
app$setInputs(assignmentpages = 5)
app$snapshot()
app$setInputs(writingpurpose = "3")
app$snapshot()
app$setInputs(draftrevise = "3")
app$snapshot()
app$setInputs(add = "click")
app$snapshot()
