app <- ShinyDriver$new("../../")
app$snapshotInit("writingItest_500wArgMinD")

app$snapshot()
app$setInputs(radio = "writing")
app$snapshot()
app$setInputs(writingName = "writing")
app$snapshot()
app$setInputs(numassign = 5)
app$snapshot()
app$setInputs(assignmentpages = 5)
app$snapshot()
app$setInputs(writtendensity = "2")
app$snapshot()
app$setInputs(writingpurpose = "2")
app$snapshot()
app$setInputs(draftrevise = "2")
app$snapshot()
app$setInputs(add = "click")
app$snapshot()
